[package]
name = "imxrt-ral"
authors = ["Tom Burdick <tom.burdick@electromatic.us>", "Ian McIntyre <ianpmcintyre@gmail.com>"]
description = "Register access layer for all NXP i.MX RT microcontrollers"
repository = "https://github.com/imxrt-rs/imxrt-ral"
readme = "README.md"
keywords = ["imxrt", "nxp", "embedded", "no_std"]
categories = ["embedded", "no-std"]
license = "MIT/Apache-2.0"
edition = "2021"
include = [
    "src/*",
    "build.rs",
    "Cargo.toml",
    "doc.md",
]
version = "0.6.1"

[package.metadata.docs.rs]
features = ["imxrt1062"]
default-target = "thumbv7em-none-eabihf"

[dependencies.cortex-m]
version = "0.7.2"
optional = true

[dependencies.ral-registers]
version = "0.1"

[lib]
bench = false
test = false

[features]
rt = []
imxrt1011 = ["cortex-m"]
imxrt1015 = ["cortex-m"]
imxrt1021 = ["cortex-m"]
imxrt1051 = ["cortex-m"]
imxrt1052 = ["cortex-m"]
imxrt1061 = ["cortex-m"]
imxrt1062 = ["cortex-m"]
imxrt1064 = ["cortex-m"]
imxrt1176_cm4 = ["cortex-m"]
imxrt1176_cm7 = ["cortex-m"]

[workspace]
members = [
    "examples/teensy4",
    "raltool",
]
