[package]
name = "imxrt-ral-examples-teensy4"
version = "0.1.0"
edition = "2024"
publish = false  # This is an example package

# The imxrt-ral dependency
#
# - Enable the 'imxrt1062' feature to specify the Teensy 4's processor
# - Enable the 'rt' feature when you're building the application
[dependencies.imxrt-ral]
path = "../.."
features = ["imxrt1062", "rt"]

# Use a runtime specialized for these MCUs.
[dependencies.imxrt-rt]
features = ["device"]
version = "0.1"

# Required when booting from flash.
[dependencies.teensy4-fcb]
version = "0.4"

# A simple panic handler!
[dependencies.teensy4-panic]
version = "0.1"

[dependencies.rtic]
version = "2.2"
features = ["thumbv7-backend"]

[dependencies.cortex-m]
version = "0.7"

[lib]
name = "imxrt_ral_shim"
path = "lib.rs"

[build-dependencies.imxrt-rt]
features = ["device"]
version = "0.1"

[[bin]]
name = "rtic-blink"
path = "rtic-blink.rs"
